### ISSUE TITLE
[ERROR] Couldn't create sautorun-rs dirs with path.

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/Autorun-rs#20] opened 2021-11-20 22:09 UTC
Getting this error quite often, happens with different things but most reliable way to recreate this would be using SF.
![image](https://user-images.githubusercontent.com/69946827/142742241-716281a4-2e79-4c6f-a390-924719402758.png)

**Comment by Vurv78** [comment] 2021-11-20 22:22
Duplicate of #19, problem is that you can provide custom chunk names which can contain invalid characters. In this case something is running with what looks like a timestamp which contains a colon which is invalid in windows filenames.

Once again solution is in the repo but still can't seem to get #17 fixed, sorry

**Closed by Vurv78** 2021-11-20 22:22 UTC
Labels: bug, priority-medium, duplicate, solution-pending
