### ISSUE TITLE
Nothing happens after injection

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/Autorun-rs#40] opened 2022-03-08 15:16 UTC
![image](https://user-images.githubusercontent.com/69946827/157267278-2cf5e894-35f3-4e08-ae3b-7019eb20993d.png)
Using v1.0.0, nothing happens after injection. Using extreme injector. Using require() in the menu state works though.

**Comment by Vurv78** [comment] 2022-03-08 21:46
Forgot to reenable it by 1.0.0 as I promised in another issue. You can build it on your own with the injector feature enabled if you really need it right now.

/
``cargo build --features runner,injector``

iirc

**Comment by Vurv78** [comment] 2022-03-08 21:47
Dupe of https://github.com/Vurv78/Autorun-rs/issues/30

**Closed** 2022-03-21 22:09 UTC
Labels: duplicate
